import { Router, type IRouter } from "express";
import healthRouter from "./health";
import categoriesRouter from "./categories";
import themesRouter from "./themes";
import contractsRouter from "./contracts";
import gisRouter from "./gis";
import opendataRouter from "./opendata";
import delibereRouter from "./delibere";
import publicationsRouter from "./publications";
import officialsRouter from "./officials";
import organiRouter from "./organi";
import reportsRouter from "./reports";
import statsRouter from "./stats";
import storageRouter from "./storage";
import questionsRouter from "./questions";
import oversightRouter from "./oversight";
import performanceRouter from "./performance";
import demographicsRouter from "./demographics";
import fundamentalActsRouter from "./fundamentalActs";
import legalityRouter from "./legality";
import bandiRouter from "./bandi";
import feedsRouter from "./feeds";
import confiscatedAssetsRouter from "./confiscatedAssets";
import accessoCivicoRouter from "./accessoCivico";
import publicRouter from "./public";
import monitoringReportsRouter from "./monitoringReports";
import helperRouter from "./helper";
import redazioneRouter from "./redazione";

const router: IRouter = Router();

router.use(healthRouter);
router.use(categoriesRouter);
router.use(themesRouter);
router.use(contractsRouter);
router.use(gisRouter);
router.use(opendataRouter);
// Register before publicationsRouter so /delibere is handled by the
// compatibility-aware archive route rather than the legacy exact-category filter.
router.use(delibereRouter);
router.use(publicationsRouter);
router.use(officialsRouter);
router.use(organiRouter);
router.use(reportsRouter);
router.use(statsRouter);
router.use(storageRouter);
router.use(questionsRouter);
router.use(oversightRouter);
router.use(performanceRouter);
router.use(demographicsRouter);
router.use(fundamentalActsRouter);
router.use(legalityRouter);
router.use(bandiRouter);
router.use(feedsRouter);
router.use(confiscatedAssetsRouter);
router.use(accessoCivicoRouter);
router.use("/public/v1", publicRouter);
router.use(monitoringReportsRouter);
router.use(helperRouter);
router.use(redazioneRouter);

export default router;
